"""'Init'

Revision ID: aab17601f663
Revises: 2b7ad3fdb243
Create Date: 2023-10-11 00:53:40.615331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab17601f663'
down_revision: Union[str, None] = '2b7ad3fdb243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
